### ISSUE TITLE
Avoid def lines in the miss statements

### ISSUE THREAD

**Issue by copitux** [ryankask/django-discoverage#5]
Regarding of [coverage FAQ](http://nedbatchelder.com/code/coverage/faq.html#faq)

> Q: Why do the bodies of functions (or classes) show as executed, but the def lines do not?
> 
> This happens because coverage is started after the functions are defined. The definition lines are executed without coverage measurement, then coverage is started, then the function is called. This means the body is measured, but the definition of the function itself is not.
> 
> To fix this, start coverage earlier. If you use the command line to run your program with coverage, then your entire program will be monitored. **If you are using the API, you need to call coverage.start() before importing the modules that define your functions.**

I have not enough experience building unittest suites and discover-runner, I guess that `build_suite` do the imports of my tests but probably I'm wrong.

So, I tried:

``` python
def run_tests(self, test_labels, extra_tests=None, **kwargs):
    cov = coverage.coverage(omit=COVERAGE_OMIT_MODULES)
    cov.start()
    if self.no_coverage:
        # ....
```

but **it doesn't work**

What it works is start the coverage at module level

``` python
coverage.start()
class DiscoverageRunner(DiscoverRunner):
```

but I don't think is a good solution

For the purpose of this issue, I show my django_project/tests structure (only what is relevant)

```
# All folders inside project as python packages (Avoiding print *inits*)
project/
  manage.py
  libs/
    app/
      models.py
  app2/
    models.py
  tests/
    app/test_*.py
    app2/test_*.py
```

and _unittest settings_

``` python
...
INSTALLED_APPS = ('libs.app', 'app2', 'discoverage')
TEST_RUNNER = 'discoverage.DiscoverageRunner'
...
```

**Comment by ryankask** [comment]
Hi copitux.

I've had this issue before and it happens (as you found in the FAQ) when you load your modules before the tests are run.

I've also just run the tests (for this project) and I can see that `accounts.utils` has 4 statements and according to the report:

```
accounts.utils            4      0   100%
```

If I alter my settings to:

```
import accounts.utils
TEST_RUNNER = 'discoverage.DiscoverageRunner'
```

The coverage report changes to...

```
accounts.utils            4      2    50%   1, 4
```

... where lines 1 and 4 contain `def` statements.

Are you loading any modules before the test runner starts?

Can you show any more of the project? I'm keen to help you if I can!

**Comment by copitux** [comment]
I've just solved, you gave me the hint :)

In the example, my `libs.app` app in the real project is more complex with multiple packages and modules inside, and a front controler in `libs.app.__init__.py` which glue _all the things_, in fact, import _all the things_ (because it works as a standalone lib and as a Django app)

So, only launching `manage.py` does the _django startup process_ and import `libs.app` and the other modules.
Thank for your support and for your wonderful app :)
